### ISSUE TITLE
No GPUs detected

### ISSUE THREAD

**Issue by rpumroy** [zhonge/cryodrgn#107]
Hi,

I've followed the anaconda installation guide to install cryoDRGN on a CentOS7 workstation. After some initial issues with figuring out pytorch versions and cuda versions, I've gotten everything installed without any errors during installation. When I run the quicktest to check the installation of cryoDRGN, the programs runs, but has the flag Use cuda False and a warning that it cannot detect any GPUs. Despite this, the program itself appears to run successfully on CPUs alone.

I followed along exactly with the posted tutorial, installing pytorch with the following command:
`conda install 'pytorch=1.7.1' cudatoolkit=11.1 -c pytorch -c nvidia`
**I tried this on two different computers, one with cuda 11.1, the other with cuda 10.0. I also tried installing cuda 10.2 on one of the computers and none of those attempts could find the GPUs.
I've tried this with the most recent cryodrgn release, 0.3.4, as well as the previous release, 0.3.3b

I'd appreciate any suggestions to get cryoDRGN working with GPUs!

**Comment by zhonge** [comment]
Sounds like there is an issue with getting [pytorch](https://pytorch.org/) installed. In a new conda environment, can you try re-installing pytorch without specifying the version? 

```
conda create -n test_pytorch python=3.7
conda install pytorch cudatoolkit=10.2 -c pytorch
```

Then, in python, you can test if the GPUs are detected with:
```
# start a python interpreter on the command line
$ python

# try to import torch and create a tensor on the GPU
> import torch
> torch.tensor([1,2,3]).cuda()
```

Slight disclaimer -- there's a compatibility issue in the latest cryodrgn release 0.3.4 with pytorch version 1.9+ (Issue https://github.com/zhonge/cryodrgn/issues/66#issuecomment-1015005378). It is currently fixed in the latest code, which is not yet an official release.

**Comment by rpumroy** [comment]
Thanks for your quick response! I checked the GPU status in python as you suggested, and it looks like we had two different issues that manifested the same way when trying to run the quicktest. I had a PyTorch version mismatch with our Cuda version - I downgraded to PyTorch 1.1 to get a version that both worked with Cuda 10.0 and ran the quicktest without errors. Seems like our installation of Cuda 10.2 just didn't work correctly, but the end readout was the same as when there was a mismatch between PyTorch and Cuda versions.

Everything is running smoothly now, thanks for your help!
