### ISSUE TITLE
.cs file as input for downsample 

### ISSUE THREAD

**Issue by epkumpu** [zhonge/cryodrgn#128]
When submitting particles to cryodrgn downsample by using a particles.cs file from cryoSPARC (in this case from an exported job), the path to the particle .mrcs is not read correctly. The path to the otherwise correct folder is prepended with a >, which causes the issue I think. If I supply the correct absolute path via --datadir, the path is added before the >, and the issue persists. I can work around this by supplying the correct paths as a .txt, but this is somewhat tedious.

Also a minor thing, --help does not yet mention that .cs files can be used as input for downsample, although the github pages do.

**Comment by zhonge** [comment]
Thank you for reporting this. It should be fixed in the top of tree, and will be available in the next release.

Btw, if all the `.mrcs` files are in a single directory, you can still use the `--datadir` flag. The code tries to prepend the datadir to the path to the .mrcs (which fails when there is the >) and to just the filename. If the .mrcs files are in different directories, you could symlink them all to the same directory, though I agree this is tedious. :)

**Comment by epkumpu** [comment]
Nice, thanks for the swift response!
