### ISSUE TITLE
Install shared cryodrgn environment for multi-user facility

### ISSUE THREAD

**Issue by andreanans** [zhonge/cryodrgn#41]
Hi,

I have a question about installing a shared cryodrgn conda environment for a multi-user facility. I used the --prefix option to install the .conda environment in a different location that is accessible to all users. 

After running the setup.py the cryodrgn software is installed in this shared .conda folder. However, somehow the path to the conda environment in my home directory is used during installation such that cryodrgn and other python scripts contain this at the start of the file: #!/home/nansa/.conda/envs/cryodrgn-0.3.1/bin/python instead of /shared/.conda/envs/cryodrgn-0.3.1/bin/python

This is causing a bunch of permissions issues since no one can read my home directory. Is there a way to trick the setup.py script to use this alternative conda path during installation?

EDIT: Adding --home to the command fixed the permissions issues
python setup.py install --home=/shared/.conda/envs/cryodrgn-0.3.1

Then I ran into this error: importlib_metadata.PackageNotFoundError: No package metadata was found for cryodrgn
I fixed it by running the normal install command:
python setup.py install

**Comment by zhonge** [comment]
Hm, I don't have any direct experience with this, but the installation should be pretty standard with conda/setuptools. In some cases I have had to comment out the install_requires block in setup.py so that it doesn't pull in incompatible versions of the dependencies (this was a special setup on a non-x86 architecture). Let me know if you were able to get it to install correctly or are still stuck with permissions.

**Comment by Guillawme** [comment]
One way that worked for me was to install conda in `/opt`, after making sure this location is not used by the OS (which is the case with most Linux distributions: `/opt` is usually left for you to install manually whatever you want). It's almost equivalent to installing in your own home directory, except you can set proper permissions on `/opt` without risking messing up permissions on your home directory (like accidentally leaving your files writable by other accounts).

Before you install anything in `/opt`, I recommend checking these two things:

- Choose appropriate permissions for `/opt`: at least, all accounts should have read and execute permissions, and the account in charge of installing programs also needs write permission. In my case, I ran `sudo chmod 777 /opt` to allow all accounts to write in `/opt` (not necessarily a good idea in general, but in my case we have so few users that it doesn't matter).
- Adjust `umask` in the `~/.bashrc` file of the account you are planning to use to install programs in `/opt` to make sure that the files this account writes are not writable by any other account. I recommend `umask u=rwx,g=rx,o=rx` (user has all permissions on their own files, other accounts in same group can read and execute but not write, and same for other accounts not in same group). Note that this account doesn't need to be in the administrative group, since you made `/opt` writable by all accounts; so, you should never need `sudo` to install programs in `/opt`.

Once you have conda in `/opt`, each user wanting to use it needs something like this in their `~/.bashrc` (adjust according to your setup; this is what conda automatically adds to the `~/.bashrc` of the account used to install conda):

```bash
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

But be careful, because this will let them modify the system-wide conda environments (if they have write permission to `/opt`). I decided to not expose conda to my users and instead expose the paths to the programs through the [Environment Modules](http://modules.sourceforge.net/) system (so they can run commands, but not mess with conda).

**Comment by andreanans** [comment]
Hi, 

I did fix the error:

conda create --prefix /path-to-shared/.conda/envs/cryodrgn-0.3.1 python=3.7
python setup.py install --home=/path-to-shared/.conda/envs/cryodrgn-0.3.1
python setup.py install
