### ISSUE TITLE
GPU RAM Requirement

### ISSUE THREAD

**Issue by EB-kim** [zhonge/cryodrgn#59]
Hi, Elllen
Is the 64GB the minimum requirement for processing or would it be different based on the amount of data that needs to be processed?

sincerely

Andy

**Comment by Guillawme** [comment]
Memory consumption directly depends on the size of your dataset, since the entire dataset is read into RAM at the beginning of a training run and stays there until the job finishes. Then I don't know how much else memory is used during training, nor whether this amount varies with epochs. But if you need to know, you can get a rough idea by running a training with a small enough dataset (say, no more than half the total amount of RAM) and keep an eye on the memory consumption reported by a system monitor during the first few epochs (I like `htop`, but it's not installed by default on most systems; on a local workstation you can use the graphical System Monitor too).

**Comment by EB-kim** [comment]
I see. Thank you, I will monitor the memory consumption.

**Comment by zhonge** [comment]
The maximum memory requirement is about 4x the size of the dataset. This could be optimized further. 

If your machine does not have enough memory, you can try training with on the fly data loading (potentially very slow if the data is not on an SSD -- see https://github.com/zhonge/cryodrgn/issues/17).
