### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by EB-kim** [zhonge/cryodrgn#60]
Hi Ellen,
I just ran the initial training but I get an assertion error. I tried to solve this but I have no idea. Do you have any suggestions to solve this problem?
![IMG_5052](https://user-images.githubusercontent.com/72215385/117385174-82e7ac00-af1f-11eb-8755-fdd70e3e9bb1.JPG)

**Comment by Guillawme** [comment]
I don't know how to help you, sorry. But one suggestion: in the future please copy/paste the text instead of posting a screen capture. It is a lot more helpful, because then the error can be searched like any text, without having to transcribe from the image first (and this issue will show up if somebody searches for the same error, which will help prevent duplicate issues).

**Comment by EB-kim** [comment]
I see, Thanks for the suggestion.

**Comment by zhonge** [comment]
There is a size mismatch in the data you provided -- 11,976 alignments in `poses.pkl` vs. 2395 particles in `subtracted.160.mrcs`.

**Comment by EB-kim** [comment]
I see. Thank you
